[package]
name = "bellman_lean"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bellman = "0.13"
bls12_381 = "0.7"
pairing = "0.22"
rand = "0.8"